### ISSUE TITLE
Patching endpoints option in netfoundry_endpoint

### ISSUE THREAD

**Issue by dariuszSki** [netfoundry/developer-tools#18]
I want to update an endpoint attributes but I cant. Is this  true or am I doing something wrong? @qrkourier

**Comment by dariuszSki** [comment]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: ERROR: got unexpected HTTP code BAD_REQUEST (400) with body {"traceId":"bd00516a3c74d791","errors":["An endpoint with that name already exists."],"status":{"code":400,"label":"Bad Request"}}
failed: [localhost] (item={'name': 'zititestnet.phx-ad-1', 'attributes': ['#us-phoenix-1', '#phx-ad-1', '#ocp']}) => {"ansible_loop_var": "item", "changed": false, "item": {"attributes": ["#us-phoenix-1", "#phx-ad-1", "#ocp"], "name": "zititestnet.phx-ad-1"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/dsliwinski/.ansible/tmp/ansible-tmp-1641688024.8708096-5630-37551059380139/AnsiballZ_netfoundry_endpoint.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/dsliwinski/.ansible/tmp/ansible-tmp-1641688024.8708096-5630-37551059380139/AnsiballZ_netfoundry_endpoint.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/dsliwinski/.ansible/tmp/ansible-tmp-1641688024.8708096-5630-37551059380139/AnsiballZ_netfoundry_endpoint.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netfoundry.platform.plugins.modules.netfoundry_endpoint', init_globals=dict(_module_fqn='ansible_collections.netfoundry.platform.plugins.modules.netfoundry_endpoint', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netfoundry_endpoint_payload_msdytpdd/ansible_netfoundry_endpoint_payload.zip/ansible_collections/netfoundry/platform/plugins/modules/netfoundry_endpoint.py\", line 234, in <module>\n  File \"/tmp/ansible_netfoundry_endpoint_payload_msdytpdd/ansible_netfoundry_endpoint_payload.zip/ansible_collections/netfoundry/platform/plugins/modules/netfoundry_endpoint.py\", line 230, in main\n  File \"/tmp/ansible_netfoundry_endpoint_payload_msdytpdd/ansible_netfoundry_endpoint_payload.zip/ansible_collections/netfoundry/platform/plugins/modules/netfoundry_endpoint.py\", line 180, in run_module\n  File \"/home/dsliwinski/.local/lib/python3.8/site-packages/netfoundry/network.py\", line 800, in create_endpoint\n    raise Exception('ERROR: got unexpected HTTP code {:s} ({:d}) with body {:s}'.format(\nException: ERROR: got unexpected HTTP code BAD_REQUEST (400) with body {\"traceId\":\"bd00516a3c74d791\",\"errors\":[\"An endpoint with that name already exists.\"],\"status\":{\"code\":400,\"label\":\"Bad Request\"}}\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by dariuszSki** [comment]
code written as this:
- name: Update endpoints type router with the same atributes as hosted edge routers of the same name
  netfoundry_endpoint:
    name: "{{ item.name }}"
    attributes: "{{ item.attributes }}"
    network: "{{ netfoundry_network.network }}"
  loop: "{{ endpoints }}"
  tags: 
    - create

**Comment by dariuszSki** [comment]
it looks like this issue is in the python module. Trying to trace it

**Comment by dariuszSki** [comment]
@qrkourier how do you test these ansible modules? The python network scripts seems to be working fine. I am not sure if this part of the code works fine in the netfoundry_endpoint.py module. Want to check if "found" list variable is populated with my endpoint.
```
# check if UUIDv4
    try: UUID(module.params['name'], version=4)
    except ValueError:
        # else assume is an Endpoint
        found = network.get_resources(type="endpoints",name=module.params['name'],typeId="Device")
    # it's a UUID and so we assign the property directly
    else: 
        found = [network.get_resource(type="endpoint",id=module.params['name'])]

    if len(found) == 0:
        if module.params['state'] == "PROVISIONED":
            result['message'] = network.create_endpoint(name=module.params['name'], attributes=module.params['attributes'], 
                session_identity=module.params['sessionIdentity'], wait=module.params['wait'])
```

**Comment by qrkourier** [comment]
@dariuszSki Do you get the same result with the latest Py module and Ansible collection?

```bash
❯ pip -q uninstall -y netfoundry && pip -q install -U netfoundry && pip show netfoundry
Name: netfoundry
Version: 5.2.9
Summary: Interface to the NetFoundry network-as-code orchestration Platform
Home-page: https://developer.netfoundry.io/guides/python/
Author: Kenneth Bingham
Author-email: support@netfoundry.io
License: MIT
Location: /home/kbingham/.pyenv/versions/3.9.0/lib/python3.9/site-packages
Requires: inflect, pyjwt, pysocks, requests
Required-by: 

❯ rm -rf ~/.ansible/collections/ansible_collections/netfoundry/platform && ansible-galaxy collection install --force-with-deps netfoundry.platform
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/netfoundry-platform-1.15.2.tar.gz to /home/kbingham/.ansible/tmp/ansible-local-1347122xnv0_3q6/tmpkq0nlt7e/netfoundry-platform-1.15.2-gt6d4d99
Installing 'netfoundry.platform:1.15.2' to '/home/kbingham/.ansible/collections/ansible_collections/netfoundry/platform'
netfoundry.platform:1.15.2 was installed successfully
```

You may also reproduce the problem with latest Py module and Ansible collection by running your playbook with Docker.

```bash
❯ docker run \
  --rm \
  --volume ~/.netfoundry/credentials.json:/netfoundry/credentials.json \
  --volume /tmp/MY_PLAYBOOK.yml:/netfoundry/playbook.yml \
  netfoundry/ansible:latest \
    ansible-playbook /netfoundry/playbook.yml
```

**Comment by dariuszSki** [comment]
````
dsliwinski@DariuszDesktop:/mnt/e/NetFoundry/Repos/azure-deploy$ pip show netfoundryName: netfoundry
Version: 5.2.9
Summary: Interface to the NetFoundry network-as-code orchestration Platform
Home-page: https://developer.netfoundry.io/guides/python/
Author: Kenneth Bingham
Author-email: support@netfoundry.io
License: MIT
Location: /home/dsliwinski/.local/lib/python3.8/site-packages
Requires: inflect, pyjwt, pysocks, requests
Required-by: 
dsliwinski@DariuszDesktop:/mnt/e/NetFoundry/Repos/azure-deploy`
```

**Comment by dariuszSki** [comment]
I have the latest one

**Comment by dariuszSki** [comment]
Is there a way to test the netfoundry_endpoint.py and step through it?

**Comment by qrkourier** [comment]
@dariuszSki Do you have the latest collection 1.15.2?

```bash
❯ jq -r '.collection_info.version' ~/.ansible/collections/ansible_collections/netfoundry/platform/MANIFEST.json 
1.15.2
```

**Comment by qrkourier** [comment]
@dariuszSki Re: simple debugging with `epdb`: https://docs.ansible.com/ansible/latest/dev_guide/debugging.html#simple-debugging

**Comment by dariuszSki** [comment]
ok, It looks like the collection is not the latest 1.14.3

**Comment by qrkourier** [comment]
I ask about the collection version because the problem you described was fixed in an earlier release.

**Comment by dariuszSki** [comment]
let me upgrade it and see if the issue clears

**Comment by qrkourier** [comment]
The problem was that routers' built-in tunnelers were filtered out by the module and so it would try to create an endpoint which then collided with the tunneler-enabled router's system-managed endpoint. Now it doesn't filter them out and instead will treat it as existing and just update attributes.

**Comment by dariuszSki** [comment]
ok, that is what I am thinking, because I noticed that you separated endpoint into device and router when using the info module

**Comment by dariuszSki** [comment]
I was looking for my endpoints under endpoints, but the were under router endpoints :)

**Comment by dariuszSki** [comment]
ok, it is good not after the upgrade

**Comment by dariuszSki** [comment]
Thanks!
